### ISSUE TITLE
Plugin Not available in Marketplace (PDI Version 8)

### ISSUE THREAD

**Issue by scrotyballbags** [FreddyFFM/PDIPlugin-AWS-SQS-Reader#1]
I can see the SNS notify authored by you in Marketplace, but not SQS reader? Will I need to go for PDI version 7?

**Comment by FreddyFFM** [comment]
Hi, 
i already added it to the marketplace but I am still waiting for approvement (https://github.com/pentaho/marketplace-metadata/pull/664).

**Comment by scrotyballbags** [comment]
Ok thanks, I have done it the manual way, though I was getting errors (java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z) until i also added the Jackson-core 2.9.3 jar file, might need to add that onto the guide.

**Comment by FreddyFFM** [comment]
Yes in both way you have to add/exchange the libraries.
I put it in the manual: https://github.com/FreddyFFM/PDIPlugin-AWS-SQS-Reader (System Requirements)

**Comment by scrotyballbags** [comment]
Ok sorry - I was following this but only saw the mention of Jackson Databind, not the others. By the way - fantastic work, this has saved me days maybe weeks of work, I hope Pentaho approve your update soon!

**Comment by FreddyFFM** [comment]
Many thanks!
