### ISSUE TITLE
SQS Reader Error in PDI

### ISSUE THREAD

**Issue by scrotyballbags** [FreddyFFM/PDIPlugin-AWS-SQS-Reader#3]
Using PDI 8.3, 
jackson-databind 2.9.8
jodatime 2.10.5
AWS java sdk 1.11.360

I have this running nicely, though it is throwing an error when retreiving SQS messages on every message. It still seems to pass the data across to the next step, but it would be nice to clear the errors for logging purposes.

2020/02/07 08:52:31 - AWS SQS Reader.0 - ERROR (version 8.3.0.0-371, build 8.3.0.0-371 from 2019-06-11 11.09.08 by buildguy) : Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
2020/02/07 08:52:31 - AWS SQS Reader.0 -  at [Source: (String)"<Notification>
2020/02/07 08:52:31 - AWS SQS Reader.0 - <NotificationMetaData>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 	<NotificationType>AnyOfferChanged</NotificationType>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 	<PayloadVersion>1.0</PayloadVersion>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 	<UniqueId>7862fb6e-7a23-493b-98de-4d97b1e1469a</UniqueId>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 	<PublishTime>2020-02-07T08:46:09.703Z</PublishTime>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 	<SellerId>A3HLB4EQMZA5MG</SellerId>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 	<MarketplaceId>A39IBJ37TRP1C6</MarketplaceId>
2020/02/07 08:52:31 - AWS SQS Reader.0 - </NotificationMetaData>
2020/02/07 08:52:31 - AWS SQS Reader.0 - <NotificationPayload>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 	<AnyOfferChangedNotification>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 		<OfferChangeTrigger>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 			<MarketplaceId>A39IBJ37TRP1C6</MarketplaceId>
2020/02/07 08:52:31 - AWS SQS Reader.0 - 			<ASIN>B07S"[truncated 10082 chars]; line: 1, column: 2]

**Comment by FreddyFFM** [comment]
Hi, 
due to being too busy with my regular job I will not be able to have a look on this soon. Maybe some updates on the libraries are needed.

**Comment by FreddyFFM** [comment]
Hi @scrotyballbags,
i now had a chance to look at the code. From the above short error extract I assume this happens on parsing the JSON. I use the JsonParseException, which provides this error message, so I do not see more details available.
For more analysis I need more information on error message and content.
